basePath: /v2
definitions:
  model.CreateProductRequest:
    properties:
      categoryId:
        type: integer
      name:
        type: string
      price:
        type: number
      sku:
        type: string
    required:
    - categoryId
    - name
    - price
    - sku
    type: object
host: http://localhost:3333/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample REST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Product API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Create a new order with the input payload
      parameters:
      - description: Create product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CreateProductRequest'
      summary: Create a new product
      tags:
      - products
swagger: "2.0"
